[pytest]

addopts=--headed 
        --browser=chromium 
        --video=retain-on-failure 
        ; --screenshot=on 
        --tracing=retain-on-failure 
        --html=myreport.html --self-contained-html --capture=tee-sys
        --alluredir=reports
